PACKAGE_ARCH = "${XUANTIE_MCPU}"
XUANTIE_PACKAGE_ARCH_SET = "YES"

XUANTIE_TUNE_CCARGS_GENERIC ?= " ${XUANTIE_TUNE_CCARGS}"

XUANTIE_MCPU_GENERIC:riscv32 ?= "c9xx-riscv32"
XUANTIE_MCPU_GENERIC:riscv64 ?= "c9xx-riscv64"
